version: "2"
services:
  web:
    image: andreipoe/firefox-send
    build:
      context: .
      args:
          - version=v3.0.22
    links:
      - redis
    ports:
      - "0.0.0.0:11443:1443"
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
    restart: unless-stopped
  redis:
    image: redis:alpine
    restart: unless-stopped
